### PR TITLE
Allow non strict octal

### PR DESCRIPTION
**Pull request by inkstak**
Hi,
I've to deal with archives that cannot be unpacked because of the following exception.

```
> Minitar.unpack(io, path)
ArgumentError: " 1213" is not a valid octal string
```

These files are provided by the french administration and can be extracted by various softwares.  
Example : https://cadastre.data.gouv.fr/data/dgfip-pci-vecteur/latest/edigeo/feuilles/52/52053/edigeo-520530000A04.tar.bz2) 

I suggest an option to try to open knowingly archives with a non strict octal :

```
Minitar.unpack(io, path, [], use_strict_octal: false)
```

An other solution might be to accept spaces as valid octal values :
```
> "       1213".oct
 => 651
> "00000001213".oct
 => 651
```
But I don't know if it can be considered as "strict".

### CODE REVIEW

**Comment by halostatue** [comment]
It might be easier to either `#trim` the string prior to using octal or to allow `' '` when parsing strict octal values, rather than introducing an new option that needs to follow several levels of code.

**Comment by halostatue** [comment]
Or I think in Ruby it’s actually `String#strip`. The reason is that in the previous issue which this was introduced in was presenting a DoS tarball because it interpreted a negative block size. I’m fine either extending the regex used to mark the octal safe (because (leading) spaces do not modify the number parsed) or running a strip on the strings before running octal on them.

**Comment by halostatue** [comment]
I like your added test, but want to improve strictness detection before adding another option.

**Comment by inkstak** [comment]
I didn't used the `#strip` method (or `#lstrip` for leading spaces) because I'm not sure what the following significant characters may be. Is it only digits ?

I notice the octal value of negative numbers uses dots. Maybe other characters are possible ?

**Comment by halostatue** [comment]
This is good, but I will not have time to release until the weekend.

**Pull request closed without merging**
